### ISSUE TITLE
Would be cool for JavaScript support

### ISSUE THREAD

**Issue by rpettyMMGY** [mcfedr/gulp-unused-images#3]
In a lot of cases I use Snap.svg and create clip-paths and masks using images. Gulp-Unused-Images doesn't track JavaScript references to images which would be nice. It's not so much an issue as it is a feature suggestion.

Overall it's been really useful and use it on everything.

**Comment by rickysullivan** [comment]
I was wanting more from this plugin too, so I decided to build my own rather than forking and hacking.

It doesn't parse html dom, but finds image files in files using a line by line / regex method. Perhaps you could give it a go on your JS?

https://www.npmjs.com/package/gulp-delete-unused-images

**Comment by mcfedr** [comment]
I'm not interested in developing this myself, but willing to look at pull requests.
I don't think its likely to be anywhere near accurate, I would always try to avoid using image directly from JS, and prefer to change css classes.
